---
- name: Update packages
  ansible.builtin.apt:
    cache_valid_time: 86400
    update_cache: yes
- name: Include nginx tasks
  ansible.builtin.include_tasks: nginx.yml
  tags: nginx
- name: Include Letsencrypt tasks
  ansible.builtin.include_tasks: letsencrypt.yml
  tags: letsencrypt
