---
- name: Install nginx and ufw
  apt:
    name:
      - nginx
      - ufw

- name: Enable nginx
  service:
    name: nginx
    enabled: true
    state: started

- name: Enable ufw
  ufw:
    state: enabled

- name: Allow HTTP
  ufw:
    rule: allow
    name: Nginx HTTP

- name: Allow HTTPS
  ufw:
    rule: allow
    name: Nginx HTTPS

- name:  Set hash bucket size
  lineinfile:
    path: "/etc/nginx/nginx.conf"
    regex: "(# )?server_names_hash_bucket_size 64;"
    line: "        server_names_hash_bucket_size 128;"
    state: present
  notify:
    - Reload nginx

- name: Setup sites
  include_tasks: site.yml
  vars:
    site: "{{ item }}"
  loop: "{{ sites }}"
  when: sites is defined

- name: Flush Handlers
  meta: flush_handlers