---
- name: Install nginx and ufw
  ansible.builtin.apt:
    name:
      - nginx
      - ufw

- name: Enable nginx
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started

- name: Enable ufw
  community.general.ufw:
    state: enabled

- name: Allow HTTP
  community.general.ufw:
    rule: allow
    name: Nginx HTTP

- name: Allow HTTPS
  community.general.ufw:
    rule: allow
    name: Nginx HTTPS

- name:  Set hash bucket size
  ansible.builtin.lineinfile:
    path: "/etc/nginx/nginx.conf"
    regex: "(# )?server_names_hash_bucket_size 64;"
    line: "        server_names_hash_bucket_size 128;"
    state: present
  notify:
    - Reload nginx

- name: Setup sites
  ansible.builtin.include_tasks: site.yml
  vars:
    site: "{{ item }}"
  loop: "{{ sites }}"
  when: sites is defined

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers