---
- name: Create html directory
  ansible.builtin.file:
    path: "/var/www/{{ site.name }}/html"
    state: directory
    mode: 0755
    owner: www-data
    group: www-data

- name: Copy html
  ansible.builtin.copy:
    src: "{{ site.files }}"
    dest: "/var/www/{{ site.name }}/html/"
    mode: 0644
    owner: www-data
    group: www-data
  when: site.type == "static"

- name: Check for existing server config
  ansible.builtin.stat:
     path: "/etc/nginx/sites-available/{{ site.name }}"
  register: site_conf

- name: Create server conf
  ansible.builtin.template:
    src: "templates/conf/site-{{ site.type }}.j2"
    dest: "/etc/nginx/sites-available/{{ site.name }}"
    mode: 0644
  when: not site_conf.stat.exists
  notify:
    - Reload nginx

- name: Enable server conf
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ site.name }}"
    dest: "/etc/nginx/sites-enabled/{{ site.name }}"
    state: link
  notify:
    - Reload nginx