---
- name: Converge
  hosts: ubuntu-focal-web
  handlers:
    - name: Update trusted certificate authority
      ansible.builtin.command: /usr/sbin/update-ca-certificates
  tasks:
    - name: Install pebble certificate
      ansible.builtin.copy:
        src: pebble/pebble.minica.crt
        dest: /usr/local/share/ca-certificates
        mode: 0600
      notify: Update trusted certificate authority
    - name: "Include ansible-web"
      ansible.builtin.include_role:
        name: "ansible-web"
      tags:
        - always
  vars:
    admin_email: admin@example.com
    sites:
      - name: example.com
        domains:
          - example.com
          - www.example.com
        files: tests/example.com/html/
        type: static
      - name: proxied.example.com
        domains:
          - proxied.example.com
        type: proxy
        proxied_server: http://127.0.0.1:8009/
    testing_flags:
      - --server
      - https://pebble:14000/dir
