---
driver:
  name: docker
platforms:
  - name: ubuntu-jammy-web
    image: ubuntu:22.04
    dockerfile: Dockerfile.j2
    privileged: true
    command: "/sbin/init"
    published_ports:
      - "0.0.0.0:443:443/tcp"
      - "0.0.0.0:80:80/tcp"
    network_mode: bridge
    docker_networks:
      - name: web
        ipam_config:
          - subnet: "10.30.50.0/16"
    networks:
      - name: web
        ipv4_address: "10.30.50.12"
    env:
      REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
  - name: pebble
    image: 'letsencrypt/pebble'
    command: "pebble"
    pre_build_image: true
    network_mode: bridge
    networks:
      - name: web
    volumes:
      - "${MOLECULE_PROJECT_DIRECTORY}/molecule/default/pebble:/test/config"
      - "${MOLECULE_PROJECT_DIRECTORY}/molecule/default/pebble/nsswitch.conf:/etc/nsswitch.conf"
    etc_hosts: { "example.com": "10.30.50.12",
                 "www.example.com": "10.30.50.12",
                 "proxied.example.com": "10.30.50.12" }
provisioner:
  name: ansible
verifier:
  name: testinfra