---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint --force-color
platforms:
  - name: ubuntu-focal-web
    image: ubuntu:focal
    dockerfile: Dockerfile.j2
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/sbin/init"
    published_ports:
      - "0.0.0.0:443:443/tcp"
      - "0.0.0.0:80:80/tcp"
provisioner:
  name: ansible
verifier:
  name: testinfra
  lint:
    name: flake8
